I attempted to run diffxpy with the number of detected genes as a covariate. This has been
proposed to improve performance on single cell data by [Soneson et al., NMeth 2018](https://www.nature.com/articles/nmeth.4612#methods).

Using that model, diffxpy fails reporting that the design matrix was not full rank.
However, the same design matrix runs flawlessly using edgeR.

Reproducible example:

```{r setup, include=FALSE}
library(reticulate)
library(readr)
library(edgeR)
knitr::knit_engines$set(python = reticulate::eng_python)
reticulate::py_available(TRUE)
# bug in rstudio/reticulate:
matplotlib <- import("matplotlib")
matplotlib$use("Agg", force = TRUE)
reticulate::py_config()
```

```{python}
import diffxpy.api as de
import pandas as pd
```

## run edgeR
```{r, message=FALSE}
counts = read_tsv("./counts.tsv")
obs = read_tsv("./obs.tsv")
```

```{r}
d <- DGEList(counts)
d <- suppressWarnings(edgeR::calcNormFactors(d))
design <- model.matrix(~ 1 + group + n_genes, data=obs)
d <- estimateDisp(d, design)
fit <- glmFit(d,design)
lrt <- glmLRT(fit, coef = 2)
pval <- lrt$table$PValue
padj <- p.adjust(pval, "BH")

# result
head(data.frame(pval = pval, padj = padj))
```

## run diffxpy
```{python}
counts = pd.read_csv("./counts.tsv", sep="\t")
obs = pd.read_csv("./obs.tsv", sep="\t")
```

```{python}
try:
  test = de.test.wald(
    data=counts.values.T,
    formula_loc="~ 1 + group + n_genes",
    factor_loc_totest=["group"],
    coef_to_test="group",
    sample_description=obs,
    batch_size=100,
    training_strategy="DEFAULT",
    dtype="float64",
    gene_names=counts.index
  )

  pd.DataFrame().assign(
    pval=test.pval,
    padj=test.qval
  )
except Exception as e:
  import traceback
  traceback.print_exc()
```
